services:
  nx-app-base:
    restart: always
    build:
      context: ../
      dockerfile: development/Dockerfile.dev
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ../:/app
      - mono-node-modules:/app/node_modules
