# `dependabot.yml` file with updates
version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # Configuration for API
  - package-ecosystem: "npm"
    directory: "/api/"
    schedule:
      interval: "weekly"
    update_configs:
      - package-regex: "^@sentry/.*"

  # Configuration for Client
  - package-ecosystem: "npm"
    directory: "/client/"
    schedule:
      interval: "weekly"
