version: "3.4"

services:
  monzodash:
    image: ghcr.io/sasharyder/monzodash:latest
    restart: unless-stopped
    links:
      - redis
      - mongo
    environment:
      - TZ=Europe/London
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - REDIS_URL=${REDIS_URL}
      - MONZO_CLIENT_ID=${MONZO_CLIENT_ID}
      - MONZO_CLIENT_SECRET=${MONZO_CLIENT_SECRET}
      - MONZODASH_DOMAIN=${MONZODASH_DOMAIN}
      - MONZODASH_WEBHOOK_DOMAIN=${MONZODASH_WEBHOOK_DOMAIN} #Optional: will fall back to MONZODASH_DOMAIN if not added

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db:/data/db

  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data

networks:
  default:
    name: docker_default
