version: "3.4"

services:
  api:
    image: node:16.13.2
    #restart: always
    ports:
      - 81:5000
    volumes:
      - ./shared:/app/shared
      - ./api:/app/api
    working_dir: /app/api
    command: >
      bash -c "yarn install && yarn start:dev"
    links:
      - redis
      - mongo
  client:
    image: node:16.13.2
    #restart: always
    ports:
      - 3000:3000
    volumes:
      - ./shared:/app/shared
      - ./client:/app/client
    working_dir: /app/client
    command: >
      bash -c "yarn install && yarn start"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  redis:
    image: redis:6.2.6-alpine
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data
    #restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
networks:
  default:
    name: docker_default
