version: "3.4"

services:
  monzodash:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - TZ=Europe/London
      - MONZO_CLIENT_ID=${MONZO_CLIENT_ID}
      - MONZO_CLIENT_SECRET=${MONZO_CLIENT_SECRET}
      - MONZODASH_DOMAIN=${MONZODASH_DOMAIN}
      - MONZODASH_WEBHOOK_DOMAIN=${MONZODASH_WEBHOOK_DOMAIN} #Optional: will fall back to MONZODASH_DOMAIN if not added

networks:
  default:
    name: docker_default
